# -*- coding: utf-8 -*-
"""ML lab(3/9).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qA4_id2f9gWJUopSQqj9Q3c8oZjE5aKN
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

dataset=pd.read_csv("/content/KMeans.csv")

dataset

x=dataset.iloc[:,[1,2]].values

import scipy.cluster.hierarchy as sch
dendrogram=sch.dendrogram(sch.linkage(x,method="ward"))
plt.show()

from sklearn.cluster import AgglomerativeClustering
hc=AgglomerativeClustering(n_clusters=5,linkage="ward")
yhc=hc.fit_predict(x)

yhc

#plot the clusters
plt.scatter(x[yhc==0,0],x[yhc==0,1],s=100,c="red",label="cluster1")
plt.scatter(x[yhc==1,0],x[yhc==1,1],s=100,c="yellow",label="cluster2")
plt.scatter(x[yhc==2,0],x[yhc==2,1],s=100,c="blue",label="cluster3")
plt.scatter(x[yhc==3,0],x[yhc==3,1],s=100,c="green",label="cluster4")
plt.scatter(x[yhc==4,0],x[yhc==4,1],s=100,c="magenta",label="cluster5")

plt.legend()

"""DBSCAN"""

from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

x=StandardScaler().fit_transform(x)

db=DBSCAN(eps=0.3,min_samples=6).fit(x)

db.labels_

db.core_sample_indices_

#Identify the boundary points
#Visualize the points in following categories:
#1. Noise Points: as black color
#2. All the cluster points as different colors
#2a. Core point size > Boundary point size
