# -*- coding: utf-8 -*-
"""Kernel based Image Filtering .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ERgA81afZUJIevi37syrp3nPx5spnZP
"""

path = r'/content/image.jpg'
import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageFilter
from scipy.ndimage import convolve

from google.colab.patches import cv2_imshow
img=cv2.imread(path)
cv2_imshow(img)

img=cv2.imread(path,cv2.IMREAD_GRAYSCALE)
cv2_imshow(img)

#kernel_declaration
identity=np.array([[0,0,0],[0,1,0],[0,0,0]])
blur=np.ones((7,7),dtype=float)*(1/80)
horizontal=np.array([])

blur

#kernel_declaration
identity=np.array([[0,0,0],[0,1,0],[0,0,0]])
blur=np.ones((7,7),dtype=float)*(1/80)
horizontal=np.array([[1,2,1],[0,0,0],[-1,-2,-1]])
# horizontal=np.array([[1,1,1],[0,0,0],[1,-2,1]])

# blur
horizontal

# kernel=blur
kernel=horizontal
img2=convolve(img,kernel)

cv2_imshow(img2)

