# -*- coding: utf-8 -*-
"""ML lab(5/11) Random_Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gW-EifhnlYlGt-965561AAHfMYK7l3i4
"""

from sklearn import datasets
iris=datasets.load_iris()

iris

import pandas as pd
data=pd.DataFrame({"Sepal length": iris.data[:,0],
                   "Sepal width": iris.data[:,1],
                   "petal length": iris.data[:,2],
                   "petal width": iris.data[:,3],
                   "species": iris.target})

data

#model training train test splitting
from sklearn.model_selection import train_test_split
x=data[["Sepal length","Sepal width","petal length","petal width"]]
y=data["species"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

#model definaion
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100)

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

iris.target_names[0]

from sklearn import metrics
metrics.accuracy_score(y_pred,y_test)

#visualizing the trees
from sklearn.tree import export_graphviz
import pydot

tree=model.estimators_[5]
export_graphviz(tree,out_file='/content/tree.dot',feature_names=iris.feature_names,rounded=True,precision=1)

(graph,)=pydot.graph_from_dot_file('tree.dot')
graph.write_png("/content/tree.png")

