# -*- coding: utf-8 -*-
"""ML lab (20/8).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11y413Qz6eJibJuU_2BZtF7yulY87AGn7

KNN Classification algorithm
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

col_names = ["sepallength","sepalwidth","petallength","petalwidth","class"]
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
dataset=pd.read_csv(url,names=col_names)

dataset

dataset_knn=dataset.values[:,0:4]
labels=dataset.values[:,-1]

dataset_knn

import math
def distance(x1,x2):
  distances=0.0
  for i in range(len(x1)):
    distances+=(x1[i]-x2[i])**2
  return math.sqrt(distances)

testing_data=dataset.values[121,0:4]

distance_cumm=[]
for i in range(len(dataset_knn)):
  distance_cumm.append([distance(dataset_knn[i],testing_data),labels[i]])

distance_cumm

distance_cumm.sort()

distance_cumm

k=7
label_topk=[]
for i in range(1,k+1):
  label_topk.append(distance_cumm[i][1])

label_topk

from collections import Counter
count=Counter(label_topk)

count

print("Our Final predicted label is ",count.most_common(1)[0][0])

