# -*- coding: utf-8 -*-
"""Exp 13: LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJgOgYUlugTtSpqWkJR_hBD9U6KRmXlz
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

from tensorflow.keras.datasets import imdb

# Load dataset
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 200

x_train = pad_sequences(x_train, maxlen=max_len)
x_test = pad_sequences(x_test, maxlen=max_len)

model = Sequential()

# Embedding Layer
model.add(Embedding(input_dim=10000, output_dim=128, input_length=max_len))

# LSTM Layer
model.add(LSTM(128))

# Output Layer
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    x_train, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

loss, accuracy = model.evaluate(x_test, y_test)
print("Test Accuracy:", accuracy)

prediction = model.predict(x_test[:1])
print("Prediction:", "Positive" if prediction[0][0] > 0.5 else "Negative")
